#!/bin/bash

# Terminate already running processes
processes=("sxhkd", "picom", "polybar", "flameshot")

for process in "${processes[@]}"; do
  if pidof -q "$process"; then
    pkill -9 -x "$process" > /dev/null; sleep 0.1
  fi
done

# Reload sxhkd daemon
flameshot &
sxhkd -c ~/.config/sxhkd/sxhkdrc &
picom --config ~/.config/picom/picom.conf &
xsetroot -cursor-name left_ptr &
~/.config/bspwm/scripts/launch_polybar.sh &
nitrogen --restore &

################---------------- Workspaces ----------------################
bspc monitor -d I II III IV V VI VII VIII IX X

################---------------- bspwm config ----------------################
# General
bspc config split_ratio         	0.5
bspc config single_monocle		true
bspc config borderless_monocle  	true
bspc config gapless_monocle		false
bspc config paddingless_monocle		true

# Border
bspc config border_width		1
bspc config window_gap			10

# Colors
bspc config normal_border_color "#282c34"
bspc config active_border_color "#282c34"
bspc config focused_border_color "#abb2bf"
bspc config presel_feedback_color "#282c34"

# Pointer(Mouse)
bspc config focus_follows_pointer	true
bspc config pointer_follows_focus	false
bspc config pointer_motion_interval	5
bspc config pointer_modifier		super
bspc config pointer_action1		move
bspc config pointer_action2		resize_side
bspc config pointer_action3		resize_corner
