[colors.primary]
background = 'dotSet(color_bg2)'
foreground = 'dotSet(color_fg3)'

[colors.normal]
black   = 'dotSet(color_bg3)'
red     = 'dotSet(color_red1)'
green   = 'dotSet(color_green1)'
yellow  = 'dotSet(color_yellow1)'
blue    = 'dotSet(color_blue1)'
magenta = 'dotSet(color_purple1)'
cyan    = 'dotSet(color_aqua1)'
white   = 'dotSet(color_fg2)'

[colors.bright]
black   = 'dotSet(color_bg4)'
red     = 'dotSet(color_red2)'
green   = 'dotSet(color_green2)'
yellow  = 'dotSet(color_yellow2)'
blue    = 'dotSet(color_blue2)'
magenta = 'dotSet(color_purple2)'
cyan    = 'dotSet(color_aqua2)'
white   = 'dotSet(color_fg4)'

[font]
size = dotSet(font_size)

[font.normal]
family = "dotSet(font)"
style = "dotSet(font_style)"

[shell]
program = "/bin/zsh"

[window]
opacity = dotSet(transparency_invert)

[window.padding]
x = 20
y = 20
