[colors]
color_01 = dotSet(color_bg3)
color_02 = dotSet(color_red1)
color_03 = dotSet(color_green1)
color_04 = dotSet(color_yellow1)
color_05 = dotSet(color_blue1)
color_06 = dotSet(color_purple1)
color_07 = dotSet(color_aqua1)
color_08 = dotSet(color_fg2)

color_09 = dotSet(color_bg4)
color_10 = dotSet(color_red2)
color_11 = dotSet(color_green2)
color_12 = dotSet(color_yellow2)
color_13 = dotSet(color_blue2)
color_14 = dotSet(color_purple2)
color_15 = dotSet(color_aqua2)
color_16 = dotSet(color_fg4)

background = dotSet(color_bg2)
foreground = dotSet(color_fg3)

[custom]
padding = 1

[settings]
screenchange-reload = true
pseudo-transparency = false

[bar/main]
width = 100%
height = dotSet(bar_height)
radius = 10

fixed-center = true

background = ${colors.background}
foreground = ${colors.foreground}

padding-left = 0
padding-right = 0
padding-bottom = 0
padding-up = 0

border-size = 5
border-color = ${colors.background}00

module-margin-left = 0
module-margin-right = 0
module-margin-up = 0

font-0 = dotSet(font):style=Bold:pixelsize=13;3
font-1 = dotSet(font):size=18;5
font-2 = unifont:fontformat=truetype:size=13:antialias=true;

modules-left = i3 windowtitle
modules-center = date
# style-switch backlight filesystem cpu memory battery network volume shutdown
modules-right = style-switch backlight filesystem temperature cpu memory battery network volume

tray-position = right
tray-padding = 2
tray-background = ${colors.background}

cursor-click = pointer
cursor-scroll = pointer

line-size = 2

enable-ipc = true

dotSet(if_bar_bottom) bottom=true

###############################################################################

[module/i3]
type = internal/i3
format = <label-state> <label-mode>
format-background = ${colors.background}

index-sort = true
wrapping-scroll = false

label-mode-padding = ${custom.padding}
label-mode-foreground = ${colors.foreground}
label-mode-background = ${colors.color_03}

; focused = Active workspace on focused monitor
label-focused = %index%
label-focused-underline = ${colors.color_11}
label-focused-padding = ${custom.padding}

; unfocused = Inactive workspace on any monitor
label-unfocused = %index%
label-unfocused-padding = ${custom.padding}

; visible = Active workspace on unfocused monitor
label-visible = %index%
label-visible-underline = ${colors.color_03}
label-visible-padding = ${custom.padding}

; urgent = Workspace with urgency hint set
label-urgent = %index%
label-urgent-padding = ${custom.padding}

; Separator in between workspaces
label-separator = ┆

[module/style-switch]
type = custom/script
exec = echo 
interval = 100
label = "  %output%  "

;format-background = ${colors.white}
format-foreground = ${colors.foreground}

click-left = ~/.scripts/switch_theme.sh -r


# TODO: Test this module with laptop
[module/backlight]
type = internal/backlight

; Use the following command to list available cards:
; $ ls -1 /sys/class/backlight/
card = intel_backlight

format = <ramp> <label>
format-background = ${colors.background}
format-padding = ${custom.padding}

; Available tokens:
;   %percentage% (default)
label = %percentage%%

ramp-foreground = ${colors.color_04}
ramp-font = 2

; Only applies if <ramp> is used
ramp-4 = "󱩖 "
ramp-3 = "󱩔 "
ramp-2 = "󱩒 "
ramp-1 = "󱩐 "
ramp-0 = "󱩎 "

[module/windowtitle]
type = internal/xwindow

format = <label>
format-background = ${colors.background}
format-padding = ${custom.padding}

format-prefix = 󱣣
format-prefix-foreground = ${colors.color_03}
format-prefix-font = 2

label = " %title%"
label-maxlen = 50
label-empty = " free"
label-separator = " "

label-empty-foreground = ${colors.color_08}


[module/volume]
type = internal/pulseaudio
format-volume =  "<ramp-volume> <label-volume>"

ramp-volume-foreground = ${colors.color_07}

ramp-volume-0 =" "
ramp-volume-0-font = 2
ramp-volume-1 =" "
ramp-volume-1-font = 2 
ramp-volume-2 =" "
ramp-volume-2-font = 2

format-volume-background = ${colors.background}
format-volume-padding = ${custom.padding}

format-muted = <label-muted>
format-muted-background = ${colors.background}
format-muted-foreground = ${colors.color_02}
format-muted-prefix = "  "
format-muted-prefix-foreground = ${colors.color_02}
format-muted-font = 2

# TODO: Test this module with laptop
[module/battery]
type = internal/battery

battery = BAT1
adapter = ACAD

full-at = 99
low-at = 5

time-format = %H%m

format-charging = <label-charging>
format-charging-background = ${colors.background}

format-charging-prefix = "󱟡 "
format-charging-prefix-font = 2
format-charging-prefix-foreground = ${colors.color_04}

format-charging-padding = ${custom.padding}

label-charging = "%percentage%%"

format-discharging = <label-discharging>
format-discharging-background = ${colors.background}

format-discharging-prefix = "󱟞 "
format-discharging-prefix-font = 2
format-discharging-prefix-foreground = ${colors.color_12}

format-discharging-padding = ${custom.padding}

label-discharging = "%percentage%%"

format-full-prefix = "󱟢 "
format-full-prefix-font = 2
format-full-prefix-foreground = ${colors.color_03}

format-full-padding = ${custom.padding}
format-full-background = ${colors.background}

label-full = "%percentage%%"

format-low-prefix = "󱟟 "
format-low-prefix-font = 2
format-low-prefix-foreground = ${colors.color_02}

format-low-padding = ${custom.padding}
format-low-background = ${colors.background}

label-low = "%percentage%%"

[module/network]
type = internal/network
interval = 2

interface = wlp3s0
interface-type = wireless

format-connected = <label-connected>
format-connected-prefix = "%{A1:$HOME/.scripts/menu_for_wifi.sh:}󱚽 %{A}"
format-connected-prefix-foreground = ${colors.color_05}
format-connected-prefix-font = 2

label-connected = %downspeed%
label-connected-font = 1

label-disconnected= %downspeed%
label-disconnected-font = 1

format-disconnected = <label-disconnected>
format-disconnected-prefix = "%{A1:$HOME/.scripts/menu_for_wifi.sh:}󱛅 %{A}"

format-disconnected-prefix-foreground = ${colors.color_02}

format-connected-background = ${colors.background}
format-disconnected-background = ${colors.background}

format-connected-padding = ${custom.padding}
format-disconnected-padding = ${custom.padding}

[module/memory]
type = internal/memory
; Seconds to sleep between updates
interval = 3

label = "%percentage_used%%"

format-prefix = " "
format-prefix-foreground = ${colors.color_12}
format-prefix-font = 2

format-background = ${colors.background}
format-padding = ${custom.padding}

[module/cpu]
type = internal/cpu

interval = 1
format = <label>
format-background = ${colors.background}
format-padding = ${custom.padding}
label = "%percentage%%"

format-prefix = "󰡵 "
format-prefix-foreground = ${colors.color_03}
format-prefix-font = 2

[module/filesystem]
type = internal/fs

mount-0 = /
interval = 10

fixed-values = true
format-mounted = <label-mounted>
format-mounted-background = ${colors.background}
format-mounted-padding = ${custom.padding}

format-mounted-prefix = " "
format-mounted-prefix-foreground = ${colors.color_06}
format-mounted-prefix-font = 2

format-unmounted = <label-unmounted>
format-unmounted-background = ${colors.background}

label-mounted = "%percentage_used%%"
label-unmounted = %mountpoint%: not mounted

[module/temperature]
type = internal/temperature
thermal-zone = 0
warn-temperature = 70

format = <ramp> <label>
format-warn = <ramp> <label-warn>
format-padding = 0 
label = %temperature%
label-warn = %temperature%
ramp-0 = ""
ramp-foreground = ${colors.color_07}

[module/date]
type = internal/date
interval = 1

date = "%a, %b %d"
time = "%H:%M:%S"

format-prefix = "󰸘 %{A1:gsimplecal:} %{A}"
format-prefix-foreground = ${colors.color_03}
format-prefix-font = 2

format-padding = ${custom.padding}
format-background = ${colors.background}
format-foreground = ${colors.foreground}

label = "%date% %time%"
